#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace f1_1s_cycle.sv --exe f1_1s_cycle_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1_1s_cycle.mk Vf1_1s_cycle

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vf1_1s_cycle
echo "\nSimulation completed"

